# Generated by Django 5.2 on 2025-05-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo',
            name='owner',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='repo',
            name='name',
            field=models.CharField(),
        ),
        migrations.AlterUniqueTogether(
            name='repo',
            unique_together={('owner', 'name')},
        ),
    ]
