# Generated by Django 5.2 on 2025-05-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_repo_owner_alter_repo_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repo',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
